### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Wolf-lbh** [marqs85/ossc#13] opened 2017-07-08 22:46 UTC

**Comment by marqs85** [comment] 2017-08-14 17:27
1. The problem comes down to timing generation, which would need to exactly match CEA specs for maximum display compatibility. That can be achieved with non-framelocked or framelocked (excl. pclk) output. The former requires a framebuffer, and the latter ideally needs a flexible clock generator, neither of which OSSC hw has since it was designed to be a simple and inexpensive line multiplier. It is possible to tweak the area of signal which is marked as active using "Adv. Timing" to get desired effect, but that typically works only on computer monitors.

2. This can be generally done via H/V backporch options in "Adv. Timing" menu.

**Closed as completed by marqs85** 2017-08-14 17:27 UTC
